FROM --platform=linux/amd64 python:3.8-slim-buster
RUN apt update && apt install libpq-dev gcc -y
RUN python3 -m ensurepip --upgrade
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY producer.py producer.py
CMD ["python3","producer.py"]