version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Prep the environment
      - echo beginning build
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3 get-pip.py
      - pip install --upgrade pip
      - pip3 install taskcat
  build:
    commands:
      - taskcat test run
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./taskcat_outputs s3://${SiteBucket}/
artifacts:
  type: zip
  files:
    - ./index.html
