services:
  producer:
    environment:
      - SQS_QUEUE_URL=https://sqs.us-east-2.amazonaws.com/531517645343/microqueue
    image: 531517645343.dkr.ecr.us-east-2.amazonaws.com/producer:latest
    x-aws-role:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Action: sqs:*
          Resource: arn:aws:sqs:us-east-2:531517645343:microqueue
  consumer:
    environment:
      - SQS_QUEUE_URL=https://sqs.us-east-2.amazonaws.com/531517645343/microqueue
    image: 531517645343.dkr.ecr.us-east-2.amazonaws.com/consumer:latest
    depends_on:
      - producer
    x-aws-role:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Action: sqs:*
          Resource: arn:aws:sqs:us-east-2:531517645343:microqueue
