SELECT bill_billing_period_start_date AS bill_billingperiodstartdate,
         bill_billing_period_end_date AS bill_billingperiodenddate,
         line_item_usage_start_date AS line_item_UsageStartDate,
         line_item_usage_end_date AS line_item_UsageEndDate,
         identity_line_item_id,
         identity_time_interval,
         bill_invoice_id,
         bill_billing_entity,
         bill_bill_type,
         bill_payer_account_id,
         line_item_usage_account_id,
         line_item_product_code,
         line_item_usage_type,
         line_item_operation,
         line_item_availability_zone,
         line_item_usage_amount,
         line_item_normalization_factor,
         line_item_normalized_usage_amount,
         line_item_currency_code,
         line_item_unblended_rate,
         line_item_blended_rate,
         line_item_blended_cost,
         line_item_tax_type,
         product_product_name,
         product_database_engine,
         product_dedicated_ebs_throughput,
         product_deployment_option,
         product_instance_family,
         product_instance_type,
         product_product_family,
         product_storage,
         product_storage_class,
         product_usagetype,
         product_usage_group,
         product_volume_type
FROM athenacurcfn_costreports_knox.costreports_knox